### ISSUE TITLE
Uneditable parts of character sheet 

### ISSUE THREAD

**Issue by Cousken** [Perfectro/Age-of-Sigmar-Soulbound-FoundryVTT#1]
The spell, talent and gear tabs in the character sheet seem to be designed to contain text yet there is no way to input text. I'm assuming this is something that broke due to Foundry updates. 

![bild](https://user-images.githubusercontent.com/232056/83950365-93cd0080-a82a-11ea-96c2-2a76b11b1d68.png)

**Comment by Perfectro** [comment]
You have to create an item and drag and drop it on the sheet.
Gere a short video : https://www.dropbox.com/s/or25wd6mx6bo96u/AgeOfSigmar-DragAndDrop.mp4?dl=0
