### ISSUE TITLE
Can't find a way to set the "preview image" for an NPC, Item, etc.

### ISSUE THREAD

**Issue by slimabob** [Perfectro/Age-of-Sigmar-Soulbound-FoundryVTT#2]
With how the NPC sheet is set up, I can't set a 'portrait' image on the top left

![image](https://user-images.githubusercontent.com/7199982/86086339-5b4dca80-ba56-11ea-83d4-66fd431ab627.png)

Here's an example of my bestiary versus PCs:

![image](https://user-images.githubusercontent.com/7199982/86086512-c5666f80-ba56-11ea-8d99-ee7d7bff88a6.png)

With a lot of monster entries it becomes challenging to quickly locate a specific npc on the fly.

I'm pretty new to FoundryVTT, so maybe there's another way to do this that I'm missing... but I can't figure anything out. Thanks for porting the system- my party can't wait to play!

**EDIT:** Here's an example of this with talents/weapons too. It would be nice to have the option to set a picture!

![image](https://user-images.githubusercontent.com/7199982/86086721-3e65c700-ba57-11ea-93b0-6addf942e001.png)

**Comment by Perfectro** [comment]
You didn't miss anything. This system doesn't offer the possibility to add an image from the interface.
You can always do it with the API but that's of course not optimal.
Anyways, I don't plan to work actively on this system so this new feature will probably never be available.
But if you do a Pull Request, I will merge it 👍

**Comment by slimabob** [comment]
Ah okay. Not really sure how to do that, but if I figure it out I'll try to contribute. Is there a way to tell the character sheet whether a weapon is ranged or melee? All of my weapons use the weapon skill pool instead of the ballistic skill pool.

**Comment by Perfectro** [comment]
@slimabob 
You need to set the `category` field.
Ranged -> accuracy
Melee -> melee
![image](https://user-images.githubusercontent.com/5683489/86492453-7aa66980-bd6e-11ea-897f-afe7dfdfbe96.png)
