### ISSUE TITLE
[Bug] Dice roller on sheet broken by 0.7.5

### ISSUE THREAD

**Issue by CharlesRampant** [Perfectro/Age-of-Sigmar-Soulbound-FoundryVTT#5]
![image](https://user-images.githubusercontent.com/37817189/97083286-cb382000-1606-11eb-9da3-ab324d7cefff.png)

Appears to happen with all sheets. Presumably something changed in the way that things are coded for dice rolling under 0.7.5.

**Comment by Perfectro** [comment]
I am working on it.
For the moment, you should stay with 0.6.6.

**Comment by Perfectro** [comment]
You can now use Foundry 0.7.5 with this system.
This version (2.0) is NOT compatible with your previous version.
Please read it before updating :
https://github.com/Perfectro/Age-of-Sigmar-Soulbound-FoundryVTT/releases/tag/v2.0
